-- 0076: the Commercial module — enquiry → internal sales order → stock hold →
--       production request → proforma → packing list → dispatch check → invoice.
--
-- WHY A NEW MODULE AND NOT THE PORTED "INTERNATIONAL SALES" ONE (owner,
-- 2026-09-05: "if they are exactly the same then good, else we'll make ours").
-- Measured on live Neon the same day: of 174 proforma_invoices only 2 were
-- generated by this ERP (81 imported, 88 granite); all 173 sales_orders are
-- imports; sales_stock_checks, sales_production_jobs, sales_packing_lists and
-- sales_packages hold 0 rows while 22 orders sit in the stages those tables
-- serve. Its stock check never reads fg_finished_slab, its packing list is one
-- line per PI item emailed to the CUSTOMER, and its numbering (PI-XXX-0001,
-- PAC-2026-00001) is not the SAL-ORD/25-26/01404 and PESPL/2780 the real
-- documents carry. Nothing there matches a stage of the owner's process
-- exactly, so nothing there is extended. Only the client master
-- (sales_clients) is shared, by foreign key.
--
-- WHAT THE OWNER DECIDED (2026-09-05):
--   * Enquiries arrive by EMAIL to Commercial; Commercial logs them. No
--     Marketing role exists (the SOP sheet's "Mktg team" line was a confusion).
--   * Stock check = Commercial picks specific AVAILABLE slabs, by batch, and
--     puts them on a 5-DAY HOLD against a reference (order / PI number). Fewer
--     slabs than required → a production request is raised.
--   * Production requests land on a Production Planning page for admins
--     (ordered queue, reorder, cleaning between designs, mark produced) BEFORE
--     any external message; the channel (Telegram / mail) is still undecided.
--   * Commercial builds the packing list. The DISPATCH TEAM — a separate team
--     on the factory floor — physically checks each slab and marks it fit or
--     unfit. Customers may want their own slab numbering and same-batch
--     grouping, so a packed slab may carry a customer-facing number and batch
--     alongside ours.
--   * Export produces the CIOT-style multi-sheet workbook from root variables;
--     domestic produces the DTA invoice (IGST 18%); delivery challans for
--     samples / display stands / the sister company are in scope.
--   * The ORDER OF STEPS and whether PAYMENT GATES anything are deliberately
--     UNDECIDED — so status is a pipeline with a timestamp per stage and no
--     hard gate. Numbering ownership (Tally or ERP) is undecided — so every
--     number is generated in the real format AND overridable by hand.
--
-- Applied 2026-09-06. To re-run (a no-op) or apply elsewhere:
--   npx prisma db execute --schema prisma/schema.prisma --file scripts/0076-commercial-module.sql
--   npx prisma generate
-- (NOT `prisma db push` — it drops undeclared columns; see CLAUDE.md and
-- scripts/NEON-PRODUCTION-RUNBOOK.md.)
--
-- PURELY ADDITIVE AND IDEMPOTENT. 18 new tables, 11 enum types, 0 new enum
-- values on existing types, 0 changes to existing tables, 31 indexes, 22
-- foreign keys — all guarded. APPLIED to Neon 2026-09-06 (verified: 18 tables,
-- 22 FKs; `prisma migrate diff` shows no drift on commercial_*). No backfill, no UPDATE, no DROP. Re-running is a
-- no-op. Every index name equals the Prisma default for the @@index/@@unique
-- declared alongside, so `prisma migrate diff` stays clean.
--
-- DESIGN NOTES
--   * Attribution columns (created_by_id, checked_by_id, ...) are plain TEXT
--     users.id with NO foreign key — the Sales/Chromia/Sampling precedent. Where
--     a screen shows a name without joining, a *_by_name column sits beside it.
--   * Money and quantities are NUMERIC, not double: rates carry 4 decimals and
--     amounts 3 because the reference documents do (3208.273 sqft × 5.4 =
--     17324.657), and a template that recomputes from rounded values disagrees
--     with the customer's copy by cents.
--   * slab_number is DOUBLE PRECISION to match fg_finished_slab.slab_number
--     (95 legacy non-integer numbers exist). It is NOT a foreign key: a packed
--     slab row is a snapshot of what was packed, and must survive the slab row
--     being corrected or re-linked.
--   * commercial_sequence is the race-safe counter every document number comes
--     from: INSERT ... ON CONFLICT DO UPDATE ... RETURNING, one row per key
--     ('SAL-ORD', 'PESPL-DTA:26-27', ...). The count()+1 pattern the ported
--     module uses collides under concurrency and drifts after any import.
--   * No CHECK constraints — Prisma cannot model them.
--
-- Read-only check before and after:
--   SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'commercial_%' ORDER BY 1;
--   SELECT typname FROM pg_type WHERE typname LIKE 'commercial_%' ORDER BY 1;

-- ───────────────────────────── enum types ─────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE "commercial_enquiry_status" AS ENUM ('NEW', 'QUOTED', 'ORDERED', 'LOST', 'CLOSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_order_kind" AS ENUM ('DOMESTIC', 'EXPORT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_order_status" AS ENUM (
    'DRAFT', 'CONFIRMED', 'STOCK_CHECKED', 'PI_ISSUED', 'PACKING', 'DISPATCH_CHECK',
    'READY', 'INVOICED', 'DISPATCHED', 'CLOSED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_po_evidence" AS ENUM ('PO', 'PI_ACKNOWLEDGED', 'EMAIL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_hold_status" AS ENUM ('ACTIVE', 'RELEASED', 'EXPIRED', 'CONSUMED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_production_status" AS ENUM ('QUEUED', 'SCHEDULED', 'IN_PRODUCTION', 'PRODUCED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_proforma_status" AS ENUM ('DRAFT', 'ISSUED', 'ACCEPTED', 'SUPERSEDED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_packing_status" AS ENUM ('DRAFT', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'FINAL', 'DISPATCHED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_fit_status" AS ENUM ('PENDING', 'FIT', 'UNFIT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_invoice_kind" AS ENUM ('DTA', 'EXPORT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "commercial_doc_status" AS ENUM ('DRAFT', 'ISSUED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── counters & settings ────────────────────────────
-- One row per numbering key. next_value is the number the NEXT document gets.
CREATE TABLE IF NOT EXISTS commercial_sequence (
  key        TEXT PRIMARY KEY,
  next_value BIGINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE commercial_sequence IS 'Race-safe document counters: INSERT … ON CONFLICT DO UPDATE … RETURNING. Key = numbering key, optionally suffixed :FY.';

-- One JSON row ('global'): numbering formats, hold days, company identity,
-- banks, default terms, tax rates. Typed defaults live in
-- src/lib/commercial/settings-defaults.ts; the row holds overrides only.
CREATE TABLE IF NOT EXISTS commercial_setting (
  id            TEXT PRIMARY KEY DEFAULT 'global',
  data          JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_by_id TEXT,                                      -- -> users.id (no hard FK)
  updated_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ───────────────────────────── client extension ───────────────────────────────
-- sales_clients has no GSTIN, PAN, state code or customer code, and the ported
-- module relies on its shape; this side table adds what a tax invoice and the
-- export workbook need without touching it.
CREATE TABLE IF NOT EXISTS commercial_client_ext (
  client_id        TEXT PRIMARY KEY,
  customer_code    TEXT,                                   -- e.g. USA-041 (marks & nos, Cust-* sheets)
  gstin            TEXT,
  pan              TEXT,
  state_code       TEXT,                                   -- GST state code, e.g. '27'
  billing_address  JSONB,                                  -- { name, lines[], country, tel }
  shipping_address JSONB,
  notify_party     JSONB,
  default_incoterm TEXT,
  default_currency TEXT,
  notes            TEXT,
  created_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP(3) NOT NULL
);
DO $$ BEGIN
  ALTER TABLE commercial_client_ext ADD CONSTRAINT commercial_client_ext_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES sales_clients(id) ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── enquiry ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commercial_enquiry (
  id             TEXT PRIMARY KEY,
  number         TEXT NOT NULL,
  client_id      TEXT,                                     -- nullable until the prospect is a client
  prospect_name  TEXT,
  contact_name   TEXT,
  contact_email  TEXT,
  contact_phone  TEXT,
  received_at    TIMESTAMP(3) NOT NULL,
  source         TEXT NOT NULL DEFAULT 'EMAIL',
  subject        TEXT,
  body           TEXT,
  status         "commercial_enquiry_status" NOT NULL DEFAULT 'NEW',
  assigned_to_id TEXT,                                     -- -> users.id (no hard FK)
  order_id       TEXT,                                     -- set when converted (plain; the order carries enquiry_id too)
  lost_reason    TEXT,
  created_by_id  TEXT,                                     -- -> users.id (no hard FK)
  created_at     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_enquiry_number_key ON commercial_enquiry (number);
-- The enquiries list: open first, newest first.
CREATE INDEX IF NOT EXISTS commercial_enquiry_status_received_at_idx ON commercial_enquiry (status, received_at);
-- "Every enquiry from this client".
CREATE INDEX IF NOT EXISTS commercial_enquiry_client_id_idx ON commercial_enquiry (client_id);
DO $$ BEGIN
  ALTER TABLE commercial_enquiry ADD CONSTRAINT commercial_enquiry_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES sales_clients(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS commercial_enquiry_item (
  id           TEXT PRIMARY KEY,
  enquiry_id   TEXT NOT NULL,
  line_no      INTEGER NOT NULL DEFAULT 1,
  design       TEXT,
  customer_sku TEXT,
  thickness    TEXT,
  finish       TEXT,
  qty_slabs    INTEGER,
  qty_sqft     NUMERIC(12,3),
  notes        TEXT,
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS commercial_enquiry_item_enquiry_id_idx ON commercial_enquiry_item (enquiry_id);
DO $$ BEGIN
  ALTER TABLE commercial_enquiry_item ADD CONSTRAINT commercial_enquiry_item_enquiry_id_fkey
    FOREIGN KEY (enquiry_id) REFERENCES commercial_enquiry(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── order (internal sales order) ───────────────────
-- The PI is the printed form of this row; its number IS the order number.
CREATE TABLE IF NOT EXISTS commercial_order (
  id                      TEXT PRIMARY KEY,
  number                  TEXT NOT NULL,                   -- SAL-ORD/26-27/01642 (format in settings; overridable)
  kind                    "commercial_order_kind" NOT NULL,
  status                  "commercial_order_status" NOT NULL DEFAULT 'DRAFT',
  client_id               TEXT NOT NULL,
  enquiry_id              TEXT,
  customer_po_number      TEXT,
  customer_po_date        DATE,
  po_evidence             "commercial_po_evidence",
  currency                TEXT NOT NULL DEFAULT 'USD',
  exchange_rate           NUMERIC(12,4),
  incoterm                TEXT,                            -- FOB / C&F / CIF / Ex-Works / DDP
  delivery_terms          TEXT,
  payment_terms           TEXT,
  payment_mode            TEXT,                            -- CAD / DP / DA / LC / Clean Credit / Advance
  bill_to                 JSONB,                           -- { name, lines[], country, tel, gstin }
  consignee               JSONB,
  notify_party            JSONB,
  buyer_if_not_consignee  JSONB,
  pre_carriage_by         TEXT,
  place_of_receipt        TEXT,
  port_of_loading         TEXT,
  port_of_discharge       TEXT,
  final_destination       TEXT,
  country_of_origin       TEXT NOT NULL DEFAULT 'India',
  country_of_destination  TEXT,
  delivery_schedule       TEXT,
  special_packing         TEXT,
  forwarder_details       TEXT,                            -- FOB: nominated forwarder
  receiver_details        TEXT,                            -- Ex-Works: nominated receiver
  customer_contact        TEXT,
  checklist               JSONB NOT NULL DEFAULT '[]'::jsonb, -- the SOP sheet's points: [{key,label,value,ok}]
  checked_by_id           TEXT,                            -- -> users.id (no hard FK)
  checked_by_name         TEXT,
  checked_at              TIMESTAMP(3),
  approved_by_id          TEXT,                            -- -> users.id (no hard FK)
  approved_by_name        TEXT,
  approved_at             TIMESTAMP(3),
  notes                   TEXT,
  -- one stamp per stage; none of them gates another (owner: order of steps undecided)
  confirmed_at            TIMESTAMP(3),
  stock_checked_at        TIMESTAMP(3),
  pi_issued_at            TIMESTAMP(3),
  packing_at              TIMESTAMP(3),
  dispatch_checked_at     TIMESTAMP(3),
  ready_at                TIMESTAMP(3),
  invoiced_at             TIMESTAMP(3),
  dispatched_at           TIMESTAMP(3),
  closed_at               TIMESTAMP(3),
  cancelled_at            TIMESTAMP(3),
  cancel_reason           TEXT,
  created_by_id           TEXT,                            -- -> users.id (no hard FK)
  created_by_name         TEXT,
  created_at              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_order_number_key ON commercial_order (number);
-- The orders board: by stage, newest first.
CREATE INDEX IF NOT EXISTS commercial_order_status_created_at_idx ON commercial_order (status, created_at);
-- "Every order of this client".
CREATE INDEX IF NOT EXISTS commercial_order_client_id_idx ON commercial_order (client_id);
DO $$ BEGIN
  ALTER TABLE commercial_order ADD CONSTRAINT commercial_order_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES sales_clients(id) ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE commercial_order ADD CONSTRAINT commercial_order_enquiry_id_fkey
    FOREIGN KEY (enquiry_id) REFERENCES commercial_enquiry(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS commercial_order_item (
  id           TEXT PRIMARY KEY,
  order_id     TEXT NOT NULL,
  line_no      INTEGER NOT NULL DEFAULT 1,
  design       TEXT,                                       -- our design name (canonical FG name)
  customer_sku TEXT,                                       -- the customer's code, e.g. VGWT10301A
  description  TEXT,                                       -- printed description, e.g. CARRARA ROYALE-Polish-Super Jumbo-30mm-Premium
  thickness    TEXT,                                       -- canonical '2 cm' / '3 cm'
  finish       TEXT,                                       -- Polish / Honed / Leathered / Suede
  size_label   TEXT,                                       -- Super Jumbo / Jumbo / Sample
  grade_label  TEXT,                                       -- Premium / Standard
  qty_slabs    INTEGER,
  qty          NUMERIC(14,3),                              -- in uom
  uom          TEXT NOT NULL DEFAULT 'SQFT',               -- SQFT / SQMT / NOS
  rate         NUMERIC(14,4),
  amount       NUMERIC(16,3),
  hsn          TEXT NOT NULL DEFAULT '68101990',
  is_sample    BOOLEAN NOT NULL DEFAULT false,
  notes        TEXT,
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP(3) NOT NULL
);
CREATE INDEX IF NOT EXISTS commercial_order_item_order_id_idx ON commercial_order_item (order_id);
DO $$ BEGIN
  ALTER TABLE commercial_order_item ADD CONSTRAINT commercial_order_item_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- The order's log: every stage move, hold, request, PI, packing list, invoice.
CREATE TABLE IF NOT EXISTS commercial_order_event (
  id       TEXT PRIMARY KEY,
  order_id TEXT NOT NULL,
  kind     TEXT NOT NULL,
  note     TEXT,
  payload  JSONB,
  by_id    TEXT,                                           -- -> users.id (no hard FK)
  by_name  TEXT,
  at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS commercial_order_event_order_id_at_idx ON commercial_order_event (order_id, at);
DO $$ BEGIN
  ALTER TABLE commercial_order_event ADD CONSTRAINT commercial_order_event_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── stock hold ─────────────────────────────────────
-- The module's record of a hold. The hold itself is fg_finished_slab.status =
-- RESERVED with reserved_for_pi = reference (changeSlabStatus 'reserve',
-- expiryDays from settings); this table says who placed it, against what, and
-- which slabs, and survives the slab rows being released or expired.
CREATE TABLE IF NOT EXISTS commercial_stock_hold (
  id              TEXT PRIMARY KEY,
  order_id        TEXT,
  enquiry_id      TEXT,
  reference       TEXT NOT NULL,                           -- what is stamped on the slabs (order / PI / enquiry number)
  customer        TEXT,
  status          "commercial_hold_status" NOT NULL DEFAULT 'ACTIVE',
  placed_by_id    TEXT,                                    -- -> users.id (no hard FK)
  placed_by_name  TEXT,
  placed_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at      TIMESTAMP(3) NOT NULL,
  released_at     TIMESTAMP(3),
  released_by_id  TEXT,                                    -- -> users.id (no hard FK)
  release_reason  TEXT,
  notes           TEXT,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP(3) NOT NULL
);
-- "What expires soon" on the dashboard.
CREATE INDEX IF NOT EXISTS commercial_stock_hold_status_expires_at_idx ON commercial_stock_hold (status, expires_at);
CREATE INDEX IF NOT EXISTS commercial_stock_hold_order_id_idx ON commercial_stock_hold (order_id);
CREATE INDEX IF NOT EXISTS commercial_stock_hold_reference_idx ON commercial_stock_hold (reference);
DO $$ BEGIN
  ALTER TABLE commercial_stock_hold ADD CONSTRAINT commercial_stock_hold_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE commercial_stock_hold ADD CONSTRAINT commercial_stock_hold_enquiry_id_fkey
    FOREIGN KEY (enquiry_id) REFERENCES commercial_enquiry(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS commercial_stock_hold_slab (
  id           TEXT PRIMARY KEY,
  hold_id      TEXT NOT NULL,
  slab_number  DOUBLE PRECISION NOT NULL,                  -- = fg_finished_slab.slab_number (snapshot, no FK)
  design       TEXT,
  thickness    TEXT,
  batch_key    TEXT,
  batch_number TEXT,
  grade        TEXT,
  length_in    DOUBLE PRECISION,
  width_in     DOUBLE PRECISION,
  sqft         NUMERIC(10,3),
  released_at  TIMESTAMP(3),
  packed_at    TIMESTAMP(3),
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_stock_hold_slab_hold_id_slab_number_key ON commercial_stock_hold_slab (hold_id, slab_number);
-- "Which hold is this slab on" from the slab side.
CREATE INDEX IF NOT EXISTS commercial_stock_hold_slab_slab_number_idx ON commercial_stock_hold_slab (slab_number);
DO $$ BEGIN
  ALTER TABLE commercial_stock_hold_slab ADD CONSTRAINT commercial_stock_hold_slab_hold_id_fkey
    FOREIGN KEY (hold_id) REFERENCES commercial_stock_hold(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── production request ─────────────────────────────
-- One row per (design, thickness) shortfall. priority is the queue order the
-- planner drags; lower runs first.
CREATE TABLE IF NOT EXISTS commercial_production_request (
  id                  TEXT PRIMARY KEY,
  order_id            TEXT,
  order_item_id       TEXT,
  enquiry_id          TEXT,
  design              TEXT NOT NULL,
  thickness           TEXT NOT NULL,
  finish              TEXT,
  qty_required        INTEGER NOT NULL,
  qty_available       INTEGER NOT NULL DEFAULT 0,
  qty_short           INTEGER NOT NULL,
  priority            INTEGER NOT NULL,
  status              "commercial_production_status" NOT NULL DEFAULT 'QUEUED',
  cleaning_note       TEXT,                                -- cleaning needed before this run (free text for now)
  planned_batch       TEXT,
  notes               TEXT,
  raised_by_id        TEXT,                                -- -> users.id (no hard FK)
  raised_by_name      TEXT,
  raised_at           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scheduled_at        TIMESTAMP(3),
  started_at          TIMESTAMP(3),
  produced_at         TIMESTAMP(3),
  produced_by_id      TEXT,                                -- -> users.id (no hard FK)
  produced_batch_keys TEXT[] NOT NULL DEFAULT '{}',
  notified_at         TIMESTAMP(3),
  notified_via        TEXT,
  cancelled_at        TIMESTAMP(3),
  created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP(3) NOT NULL
);
-- The planning queue itself.
CREATE INDEX IF NOT EXISTS commercial_production_request_status_priority_idx ON commercial_production_request (status, priority);
CREATE INDEX IF NOT EXISTS commercial_production_request_order_id_idx ON commercial_production_request (order_id);
DO $$ BEGIN
  ALTER TABLE commercial_production_request ADD CONSTRAINT commercial_production_request_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE commercial_production_request ADD CONSTRAINT commercial_production_request_enquiry_id_fkey
    FOREIGN KEY (enquiry_id) REFERENCES commercial_enquiry(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── proforma invoice ───────────────────────────────
-- A revision-stamped snapshot of the order at the moment the PI was issued. The
-- PDF is rendered from snapshot, never from the live order, so a PI the
-- customer holds cannot change under them.
CREATE TABLE IF NOT EXISTS commercial_proforma (
  id            TEXT PRIMARY KEY,
  order_id      TEXT NOT NULL,
  number        TEXT NOT NULL,                             -- = order number by default
  revision      INTEGER NOT NULL DEFAULT 0,
  status        "commercial_proforma_status" NOT NULL DEFAULT 'DRAFT',
  issued_at     TIMESTAMP(3),
  valid_until   DATE,
  accepted_at   TIMESTAMP(3),
  superseded_at TIMESTAMP(3),
  snapshot      JSONB NOT NULL,
  currency      TEXT NOT NULL DEFAULT 'USD',
  total_amount  NUMERIC(16,3),
  notes         TEXT,
  created_by_id TEXT,                                      -- -> users.id (no hard FK)
  created_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_proforma_number_revision_key ON commercial_proforma (number, revision);
CREATE INDEX IF NOT EXISTS commercial_proforma_order_id_idx ON commercial_proforma (order_id);
DO $$ BEGIN
  ALTER TABLE commercial_proforma ADD CONSTRAINT commercial_proforma_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── packing list ───────────────────────────────────
CREATE TABLE IF NOT EXISTS commercial_packing_list (
  id                TEXT PRIMARY KEY,
  order_id          TEXT NOT NULL,
  number            TEXT NOT NULL,
  status            "commercial_packing_status" NOT NULL DEFAULT 'DRAFT',
  container_no      TEXT,
  seal_no           TEXT,
  liner_otl_no      TEXT,
  vehicle_no        TEXT,
  gross_weight_kg   NUMERIC(12,2),
  net_weight_kg     NUMERIC(12,2),
  packages_summary  TEXT,                                  -- e.g. "07 Wooden Crate(S) + 08 Sample Box"
  notes             TEXT,
  created_by_id     TEXT,                                  -- -> users.id (no hard FK)
  created_by_name   TEXT,
  submitted_at      TIMESTAMP(3),
  submitted_by_id   TEXT,                                  -- -> users.id (no hard FK)
  verified_at       TIMESTAMP(3),
  verified_by_id    TEXT,                                  -- -> users.id (no hard FK)
  verified_by_name  TEXT,
  verification_note TEXT,
  finalised_at      TIMESTAMP(3),
  dispatched_at     TIMESTAMP(3),
  created_at        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_packing_list_number_key ON commercial_packing_list (number);
CREATE INDEX IF NOT EXISTS commercial_packing_list_order_id_idx ON commercial_packing_list (order_id);
-- The dispatch team's queue: SUBMITTED, oldest first.
CREATE INDEX IF NOT EXISTS commercial_packing_list_status_submitted_at_idx ON commercial_packing_list (status, submitted_at);
DO $$ BEGIN
  ALTER TABLE commercial_packing_list ADD CONSTRAINT commercial_packing_list_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS commercial_crate (
  id              TEXT PRIMARY KEY,
  packing_list_id TEXT NOT NULL,
  crate_no        INTEGER NOT NULL,
  kind            TEXT NOT NULL DEFAULT 'Wooden Crate',    -- Wooden Crate / Sample Box / Bundle
  gross_kg        NUMERIC(10,2),
  net_kg          NUMERIC(10,2),
  length_cm       NUMERIC(8,1),
  width_cm        NUMERIC(8,1),
  height_cm       NUMERIC(8,1),
  remarks         TEXT,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_crate_packing_list_id_crate_no_key ON commercial_crate (packing_list_id, crate_no);
DO $$ BEGIN
  ALTER TABLE commercial_crate ADD CONSTRAINT commercial_crate_packing_list_id_fkey
    FOREIGN KEY (packing_list_id) REFERENCES commercial_packing_list(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- One row per slab on a packing list: our record AND the customer-facing one.
CREATE TABLE IF NOT EXISTS commercial_packed_slab (
  id                TEXT PRIMARY KEY,
  packing_list_id   TEXT NOT NULL,
  crate_id          TEXT,
  slab_number       DOUBLE PRECISION NOT NULL,             -- ours (= fg_finished_slab.slab_number; snapshot, no FK)
  customer_slab_no  TEXT,                                  -- the customer's numbering, if they want their own
  customer_batch_no TEXT,
  design            TEXT,
  customer_sku      TEXT,
  thickness         TEXT,
  batch_key         TEXT,
  batch_number      TEXT,
  grade             TEXT,
  length_cm         NUMERIC(8,1),
  width_cm          NUMERIC(8,1),
  sqm               NUMERIC(10,4),
  sqft              NUMERIC(10,3),
  fit               "commercial_fit_status" NOT NULL DEFAULT 'PENDING',
  unfit_reason      TEXT,
  checked_by_id     TEXT,                                  -- -> users.id (no hard FK)
  checked_at        TIMESTAMP(3),
  sort_order        INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_packed_slab_packing_list_id_slab_number_key ON commercial_packed_slab (packing_list_id, slab_number);
CREATE INDEX IF NOT EXISTS commercial_packed_slab_slab_number_idx ON commercial_packed_slab (slab_number);
CREATE INDEX IF NOT EXISTS commercial_packed_slab_crate_id_idx ON commercial_packed_slab (crate_id);
DO $$ BEGIN
  ALTER TABLE commercial_packed_slab ADD CONSTRAINT commercial_packed_slab_packing_list_id_fkey
    FOREIGN KEY (packing_list_id) REFERENCES commercial_packing_list(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE commercial_packed_slab ADD CONSTRAINT commercial_packed_slab_crate_id_fkey
    FOREIGN KEY (crate_id) REFERENCES commercial_crate(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── invoice (DTA or export) ────────────────────────
CREATE TABLE IF NOT EXISTS commercial_invoice (
  id              TEXT PRIMARY KEY,
  order_id        TEXT NOT NULL,
  packing_list_id TEXT,
  kind            "commercial_invoice_kind" NOT NULL,
  number          TEXT NOT NULL,                           -- PESPL/2780 (export) · PESPL/0137/26-27 (DTA)
  invoice_date    DATE NOT NULL,
  status          "commercial_doc_status" NOT NULL DEFAULT 'DRAFT',
  currency        TEXT NOT NULL,
  exchange_rate   NUMERIC(12,4),
  snapshot        JSONB NOT NULL,                          -- everything the PDF / workbook needs
  subtotal        NUMERIC(16,3),
  tax_type        TEXT,                                    -- IGST / CGST_SGST / NONE
  tax_rate        NUMERIC(6,2),
  igst            NUMERIC(16,2),
  cgst            NUMERIC(16,2),
  sgst            NUMERIC(16,2),
  round_off       NUMERIC(8,2),
  grand_total     NUMERIC(16,2),
  amount_in_words TEXT,
  vehicle_no      TEXT,
  transporter     TEXT,
  lr_no           TEXT,
  container_no    TEXT,
  seal_no         TEXT,
  eway_bill_no    TEXT,
  notes           TEXT,
  created_by_id   TEXT,                                    -- -> users.id (no hard FK)
  issued_at       TIMESTAMP(3),
  cancelled_at    TIMESTAMP(3),
  cancel_reason   TEXT,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_invoice_number_key ON commercial_invoice (number);
CREATE INDEX IF NOT EXISTS commercial_invoice_order_id_idx ON commercial_invoice (order_id);
-- The invoice register: by kind and date.
CREATE INDEX IF NOT EXISTS commercial_invoice_kind_invoice_date_idx ON commercial_invoice (kind, invoice_date);
DO $$ BEGIN
  ALTER TABLE commercial_invoice ADD CONSTRAINT commercial_invoice_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE commercial_invoice ADD CONSTRAINT commercial_invoice_packing_list_id_fkey
    FOREIGN KEY (packing_list_id) REFERENCES commercial_packing_list(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── delivery challan ───────────────────────────────
-- Samples, display stands, goods to the sister company: a movement, not a sale.
CREATE TABLE IF NOT EXISTS commercial_delivery_challan (
  id                  TEXT PRIMARY KEY,
  number              TEXT NOT NULL,                       -- PESPL/DC/20/26
  challan_date        DATE NOT NULL,
  order_id            TEXT,
  consignee_client_id TEXT,
  consignee_name      TEXT NOT NULL,
  consignee_address   TEXT,
  consignee_gstin     TEXT,
  po_ref              TEXT,                                -- 'Verbal' is a real value here
  commodity           TEXT,
  purpose             TEXT,                                -- printed note, e.g. display purposes only, not for sale
  items               JSONB NOT NULL DEFAULT '[]'::jsonb,  -- [{ description, qty, unit, sqft, rate, amount, hsn }]
  total_amount        NUMERIC(14,2),
  amount_in_words     TEXT,
  lorry_no            TEXT,
  notes               TEXT,
  status              "commercial_doc_status" NOT NULL DEFAULT 'DRAFT',
  created_by_id       TEXT,                                -- -> users.id (no hard FK)
  issued_at           TIMESTAMP(3),
  cancelled_at        TIMESTAMP(3),
  created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_delivery_challan_number_key ON commercial_delivery_challan (number);
CREATE INDEX IF NOT EXISTS commercial_delivery_challan_challan_date_idx ON commercial_delivery_challan (challan_date);
DO $$ BEGIN
  ALTER TABLE commercial_delivery_challan ADD CONSTRAINT commercial_delivery_challan_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES commercial_order(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE commercial_delivery_challan ADD CONSTRAINT commercial_delivery_challan_consignee_client_id_fkey
    FOREIGN KEY (consignee_client_id) REFERENCES sales_clients(id) ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────── export document set ────────────────────────────
-- The root variables the CIOT-style workbook is generated from, kept so the
-- same workbook can be regenerated byte-for-byte and edited later.
CREATE TABLE IF NOT EXISTS commercial_export_doc_set (
  id               TEXT PRIMARY KEY,
  invoice_id       TEXT NOT NULL,
  root_variables   JSONB NOT NULL,
  template_version TEXT,
  generated_at     TIMESTAMP(3),
  generated_by_id  TEXT,                                   -- -> users.id (no hard FK)
  created_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_export_doc_set_invoice_id_key ON commercial_export_doc_set (invoice_id);
DO $$ BEGIN
  ALTER TABLE commercial_export_doc_set ADD CONSTRAINT commercial_export_doc_set_invoice_id_fkey
    FOREIGN KEY (invoice_id) REFERENCES commercial_invoice(id) ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
